services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quibble-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quibble-celery-worker
    restart: unless-stopped
    env_file:
      - ./backend/.env
    command: celery -A config worker --loglevel=info --concurrency=4
