services:
  backend:
    image: 903050880736.dkr.ecr.ap-south-1.amazonaws.com/goquibble/quibble:latest
    container_name: quibble-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"

  celery-worker:
    image: 903050880736.dkr.ecr.ap-south-1.amazonaws.com/goquibble/quibble:latest
    container_name: quibble-celery-worker
    restart: unless-stopped
    env_file:
      - .env
    command: celery -A config worker --loglevel=info --concurrency=1
