# Generated by Django 5.2.6 on 2025-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
