# Generated by Django 5.2.6 on 2025-09-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0002_alter_quib_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
