# Generated by Django 5.2.6 on 2025-09-29 15:20

import django_resized.forms
import quib.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0003_alter_quib_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='cover_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=1, scale=None, size=[300, None], upload_to=quib.models.Quib.cover_small_upload_path),
        ),
    ]
