# Generated by Django 5.2.6 on 2025-09-29 16:47

import django_resized.forms
import quib.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0004_alter_quib_cover_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='cover_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=1, scale=None, size=[100, 100], upload_to=quib.models.Quib.cover_small_upload_path),
        ),
    ]
