# Generated by Django 5.2.6 on 2025-10-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quib', '0005_alter_quib_cover_small'),
        ('user', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuibVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('quib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quib.quib')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quib_votes', to='user.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quib', 'voter'), name='unique_quib_voter')],
            },
        ),
    ]
