# Generated by Django 5.2.6 on 2025-09-25 09:36

import core.utils
import core.validators
import django.db.models.functions.text
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiblet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], upload_to=core.utils.get_avatar_upload_path)),
                ('type', models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted'), ('PRIVATE', 'Private')], default='PUBLIC')),
                ('name', models.CharField(error_messages={'unique': 'Quiblet with this name already exists.'}, max_length=25, unique=True, validators=[core.validators.UsernameValidator()])),
                ('description', models.TextField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('nsfw', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(related_name='joined_communities', to='user.profile')),
                ('moderators', models.ManyToManyField(related_name='moderated_communities', to='user.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_quiblet_name_case_insensitive')],
            },
        ),
    ]
