# Generated by Django 5.2.6 on 2025-09-25 09:43

import core.utils
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiblet',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1200, 300], upload_to=core.utils.get_banner_upload_path),
        ),
    ]
