# Generated by Django 5.2.7 on 2026-02-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quibletmember',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
