# Generated by Django 5.2.7 on 2026-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0002_quibletmember_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='quib',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
