# Generated by Django 5.2.7 on 2026-02-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0003_quib_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
