# Generated by Django 5.2.7 on 2025-10-03 11:38

import django.db.models.deletion
import django_resized.forms
import django_shortuuid.fields
import quiblet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0003_alter_quiblet_members_alter_quiblet_moderators'),
        ('user', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quib',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', django_shortuuid.fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', blank=True, collision_check=True, editable=False, length=7, max_length=7, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to=quiblet.models.Quib.cover_upload_path)),
                ('cover_small', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=1, scale=None, size=[100, 100], upload_to=quiblet.models.Quib.cover_small_upload_path)),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quibs', to='user.profile')),
                ('quiblet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quibs', to='quiblet.quiblet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuibVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('quib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quiblet.quib')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quib_votes', to='user.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quib', 'voter'), name='unique_quib_voter')],
            },
        ),
    ]
