# Generated by Django 5.2.7 on 2026-02-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0004_comment_is_moderator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiblet',
            old_name='avatar',
            new_name='avatar_url',
        ),
    ]
