# Generated by Django 5.2.7 on 2025-10-05 02:12

import django_shortuuid.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0005_alter_quib_cover_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='id',
            field=django_shortuuid.fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', blank=True, collision_check=False, editable=False, length=7, max_length=7, max_retries=10, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
