# Generated by Django 5.2.6 on 2025-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0002_quiblet_banner'),
        ('user', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiblet',
            name='members',
            field=models.ManyToManyField(related_name='joined_quiblets', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='quiblet',
            name='moderators',
            field=models.ManyToManyField(related_name='moderated_quiblets', to='user.profile'),
        ),
    ]
