# Generated by Django 5.2.7 on 2025-10-03 14:25

import django_resized.forms
import quiblet.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0004_quib_quibvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quib',
            name='cover_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], editable=False, force_format='WEBP', keep_meta=True, null=True, quality=1, scale=None, size=[100, 100], upload_to=quiblet.models.Quib.cover_small_upload_path),
        ),
    ]
