# Generated by Django 5.2.7 on 2025-10-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0006_alter_quib_id'),
        ('user', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiblet',
            name='members',
        ),
        migrations.RemoveField(
            model_name='quiblet',
            name='moderators',
        ),
        migrations.CreateModel(
            name='QuibletMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderator', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_quiblets', to='user.profile')),
                ('quiblet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='quiblet.quiblet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('quiblet', 'member'), name='unique_quiblet_member')],
            },
        ),
    ]
