# Generated by Django 5.2.7 on 2025-10-19 03:35

import django.db.models.deletion
import django_ltree.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0007_remove_quiblet_members_remove_quiblet_moderators_and_more'),
        ('user', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django_ltree.fields.PathField(unique=True)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='user.profile')),
                ('quib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quiblet.quib')),
            ],
            options={
                'ordering': ('path',),
                'abstract': False,
            },
        ),
    ]
