# Generated by Django 5.2.7 on 2025-10-19 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiblet', '0008_comment'),
        ('user', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quiblet.comment')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_votes', to='user.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('comment', 'voter'), name='unique_comment_voter')],
            },
        ),
    ]
