# Generated by Django 5.2.7 on 2026-02-09 12:54

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_search', '0001_initial'),
        ('quiblet', '0004_comment_is_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuibEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('quib', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='quiblet.quib')),
            ],
        ),
    ]
