# Generated by Django 5.2.6 on 2025-09-17 11:54

import core.utils
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], upload_to=core.utils.get_avatar_upload_path),
        ),
    ]
