# Generated by Django 5.2.6 on 2025-09-23 02:37

import core.utils
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], upload_to=core.utils.get_avatar_upload_path),
        ),
    ]
